Date and time
KarlisTi/Codelex_Java pull request #4
Opened 2022-03-17 16:34 UTC by KarlisTi

2022-03-23 09:03 UTC, NilsKula requested changes
trūskt otrā :thinking:

2022-03-23 09:03 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/DatePeriod.java
> +    public static void intersection(LocalDate firstStart, LocalDate firstEnd, LocalDate secondStart, LocalDate secondEnd) {
`The intersection method should receive DatePeriod as a parameter and return DatePeriod - the intersection of both periods.`

2022-03-24 16:26 UTC, KarlisTi commented
> trūskt otrā 🤔

atradu otro, bija ieklīdis citā package.
Teikšu, ka diezgan bieži ir sanācis Intelli J, ka netīšām pārvelkas java failu citā package

2022-03-24 22:36 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/DatePeriod.java
> +    public static void intersection(LocalDate firstStart, LocalDate firstEnd, LocalDate secondStart, LocalDate secondEnd) {
unfortunately it be like that sometimes, happens to everyone 😄

2022-03-24 22:38 UTC, NilsKula reviewed
ja pārvelkas uz citu package, tad jau tāpat fails rādītos pie commit? 
varbūt pilnībā neiebraucu problēma, droši uzraksti par to slack man vai jānim ja nu kas 😄

2022-03-29 08:45 UTC, KarlisTi reviewed
Done

2022-03-29 08:45 UTC, KarlisTi commented on src/main/java/io/codelex/dateandtime/practice/DatePeriod.java
> +    public static void intersection(LocalDate firstStart, LocalDate firstEnd, LocalDate secondStart, LocalDate secondEnd) {
Uzliku private

2022-03-30 11:13 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/DatePeriod.java
> +    public static void intersection(LocalDate firstStart, LocalDate firstEnd, LocalDate secondStart, LocalDate secondEnd) {
šis jau bija tas kurš pietrūka :smile:

2022-03-30 11:16 UTC, NilsKula requested changes

2022-03-30 11:16 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/DatePeriod.java
> +   private static void intersection(LocalDate firstStart, LocalDate firstEnd, LocalDate secondStart, LocalDate secondEnd) {
tas ko atgriež jau bija jāparmaina, varbūt aizmirsi commit uztaisīt?

2022-04-10 06:47 UTC, janistumpelis commented
@KarlisTi Šeit uzdevumi nav pabeigti, izlasi vēlreiz 3. uzdevuma nosacījumus un izlabo kodu.

2022-04-15 17:49 UTC, NilsKula approved these changes
divas mazas lietas

2022-04-15 17:49 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/PeriodOfDate/DatePeriod.java
> +    public boolean overlapPeriods(DatePeriod secondPeriod) {
šis metodes tad private sanāks

2022-04-15 17:49 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/practice/PeriodOfDate/DatePeriod.java
> +        return secondPeriod.start.isBefore(this.start) && secondPeriod.end.isAfter(this.start) ||
operator in new line

2022-04-27 14:07 UTC, merged